services:
  gluster1:
    image: ${IMAGE_NAME}
    privileged: true
    environment:
      LEADER: "true"
      ME: "gluster1"
      PEER1: "gluster2"
      PEER2: "gluster3"
      TIMEOUT1: $TIMEOUT1
      TIMEOUT2: $TIMEOUT2
  gluster2:
    image: ${IMAGE_NAME}
    privileged: true
    environment:
      LEADER: "false"
      ME: "gluster2"
      PEER1: "gluster1"
      PEER2: "gluster3"
      TIMEOUT1: $TIMEOUT1
      TIMEOUT2: $TIMEOUT2
  gluster3:
    image: ${IMAGE_NAME}
    privileged: true
    environment:
      LEADER: "false"
      ME: "gluster3"
      PEER1: "gluster1"
      PEER2: "gluster2"
      TIMEOUT1: $TIMEOUT1
      TIMEOUT2: $TIMEOUT2
